server:
  port: 8085
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true # 开启Feign对Sentinel的整合
spring:
  rabbitmq:
    host: ${rabbit.host}
    port: ${rabbit.port}
    virtual-host: ${rabbit.virtual-host}
    username: ${rabbit.username}
    password: ${rabbit.password}
